apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    installationDescription: ""
    ucp.metadata.generation: "1"
  generation: 2
  name: helpme
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: registry-pull-only-credentials-installer.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
  serviceAccountName: pkg-installs-sa
  values:
    - secretRef:
        name: helpme
