apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  serviceAccountName: fluxcd-helmrelease-installer
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: rabbitmq
      version: 14.6.3
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
      interval: 5m
  releaseName: rabbitmq
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: rabbitmq-values
