# podinfo-values.yaml
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-values
type: Opaque
stringData:
  values.yaml: |
    image:
      repository: harbor.lab.brianragazzi.com/library/podinfo
      tag: latest
    replicaCount: 3
    serviceAccount:
      imagePullSecrets:
        - name: tanzu-sidecar-fetch-cred
